src/Munazara.Web/Controllers/TopicController.cs
using Munazara.Application.DataService.Category;
using Munazara.Application.DataService.Topic;
using Munazara.Application.DataService.Topic.Request;
using Munazara.Web.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Munazara.Web.Controllers

{
    public class TopicController : BaseController
    {
        private ITopicService topicService;
        private ICategoryService categoryService;

        public TopicController(ITopicService topicService, ICategoryService categoryService)
        {
            this.topicService = topicService;
            this.categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            var model = topicService.GetTopicDetail(id);
            if (model == null)
            {
                return Redirect("/");
            }
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            CreateTopicViewModel model = new CreateTopicViewModel
            {
                Categories = categoryService.GetCategories().Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name })
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(CreateTopicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = categoryService.GetCategories().Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name });
                return View(model);
            }
            try
            {
                CreateTopicRequest request = new CreateTopicRequest
                {
                    CategoryId = model.Category,
                    Content = model.Content,
                    MemberId = Convert.ToInt32(User.Identity.Name),
                    Title = model.Title
                };

                var response = topicService.CreateTopic(request);
                return RedirectToAction("Detail", new { Id = response.Id });
            }
            catch (Exception ex)
            {
                Error(ex);

                model.Categories = categoryService.GetCategories().Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name, Selected = model.Category == x.Id });
                return View(model);
            }
        }
    }
}

src/Munazara.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->

    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    <div class="navbar navbar-inverse set-radius-zero">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">

                    <img src="/Content/img/logo.png" />
                </a>
            </div>
            @if (Request.IsAuthenticated)
            {
                <div class="right-div">
                    @Html.ActionLink("ÇIKIŞ","Logout","Account", null,new {@class="btn btn-info pull-right" })
                </div>
                <div class="right-div">
                    @Html.ActionLink("Konu Başlat", "Create", "Topic",null, new { @class = "btn btn-success pull-right" })
                </div>
            }
            else
            {
                <div class="right-div">
                    @Html.ActionLink("KAYIT", "Register", "Account", null, new { @class = "btn btn-info pull-right" })
                </div>
                <div class="right-div">
                    @Html.ActionLink("GİRİŞ", "Login", "Account", null, new { @class = "btn btn-success pull-right" })
                </div>
            }
        </div>
    </div>
    <section class="menu-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-collapse collapse ">
                        <ul id="menu-top" class="nav navbar-nav navbar-left">
                            <li>
                                @Html.ActionLink("Anasayfa", "Index", "Home")

                            <li>

                                <a href="#" class="dropdown-toggle" id="ddlmenuItem" data-toggle="dropdown">Kategoriler <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="ddlmenuItem">
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="ui.html">Soru</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="ui.html">Öneri</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Falanlar Filanlar</a></li>
                                </ul>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="content-wrapper">
        <div class="container">

            @RenderBody()
        </div>
    </div>
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    &copy; 2014 Yourdomain.com |<a href="http://www.binarytheme.com/" target="_blank"> Designed by : binarytheme.com</a>
                </div>
            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/scripts")

    @RenderSection("scripts", required: false)
</body>
</html>